# configs/main.yaml
# ------------------------------------------------------------------
# Minimal, end‑to‑end configuration that matches the code layout
# we just finished wiring up (Hydra + Gatherer + loop stage).
# ------------------------------------------------------------------

hydra:
  run:
    dir: "outputs/${now:%Y%m%d_%H%M%S}"   # keep Hydra logs tidy

# ------------------------------------------------------------------
# step_fn : tells KimConvergence which file implements the per‑step
#           dynamics *and* passes its hyper‑parameters.
# ------------------------------------------------------------------

step_fn:
  fname: brownian_oscillator.py
  max_steps: 1e9            # maximum steps
  params:
    seed: 1234                # random‑number generator seed
    kB: 1.0                   # Boltzmann constant (reduced units)
    temperature: 0.2            # T
    lam: 1                   # damping coefficient
    k_spring: 5.0             # harmonic force constant
    dt: 1e-3                  # integration time step
    x_init: 69420.0            # initial position
    substeps: 10000

# ------------------------------------------------------------------
# Pipeline order
# ------------------------------------------------------------------
pipeline:
  stages:
    - equilibrate
    - production

# ------------------------------------------------------------------
# Stage definitions
# ------------------------------------------------------------------

equilibrate:
  # Hyper‑parameters read in stages/equilibrate.py
  percent_past_d: 2
  every: 100
  key: position

  gather:
    init_callbacks:
    step_callbacks:
    cleanup_callbacks:

production:
  # Hyper‑parameters read in stages/production.py
  c: 5
  tol: 100
  key: position

  gather:
    init_callbacks:
    step_callbacks:
    cleanup_callbacks: